[project]
name = "ChuckChugsGuinness"
version = "0.1.0"
description = "Scripts for fetching and calculating Guinness drinking stats, possibly from YouTube."
requires-python = ">=3.7" # Assuming a common recent version
dependencies = [
  "google-api-python-client"
]
