[project]
name = "PoopMap"
version = "0.1.0"
description = "Scripts for generating statistics and map data related to 'poop map', using pandas and geopy."
requires-python = ">=3.7" # Assuming a common recent version
dependencies = [
  "pandas",
  "geopy"
]
